apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myappreplica
    type: frontend
spec:
  template:
    #Now the POD details are entered.
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
        containers:
          - name: nginx-container
            image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: myapp #This has to match the label in the metadata of the POD.
